Traceback (most recent call last):
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import random

def add_noise(x, mu=0, sd=1):
  """Adds gaussian noise to the input.

  Parameters
  ----------
  x : number
    The number to add noise to.
  mu : float, optional
    The mean of the gaussian noise distribution.
    Default: 0
  sd : float, optional
    The standard deviation of the noise distribution.
    Default: 1

  Returns
  -------
  float
  """

noise = random.normalvariate(mu, sd)
return x + noise
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 22[0m
[1;32m      3[0m [38;5;28;01mdef[39;00m [38;5;21madd_noise[39m(x, mu[38;5;241m=[39m[38;5;241m0[39m, sd[38;5;241m=[39m[38;5;241m1[39m):
[1;32m      4[0m [38;5;250m  [39m[38;5;124;03m"""Adds gaussian noise to the input.[39;00m
[1;32m      5[0m 
[1;32m      6[0m [38;5;124;03m  Parameters[39;00m
[0;32m   (...)[0m
[1;32m     19[0m [38;5;124;03m  float[39;00m
[1;32m     20[0m [38;5;124;03m  """[39;00m
[0;32m---> 22[0m noise [38;5;241m=[39m random[38;5;241m.[39mnormalvariate([43mmu[49m, sd)
[1;32m     23[0m [38;5;28;01mreturn[39;00m x [38;5;241m+[39m noise

[0;31mNameError[0m: name 'mu' is not defined

